eureka:
  client:
    service-url:
      defaultZone: http://localhost:8773/eureka/
server:
  port: 8768
spring:
  application:
    name: service-miya
    # zipkin 服务链路追踪配置
  zipkin:
    base-url: http://localhost:9411/

